# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
    example-workflow:
      jobs:
        - cypress/run:
            start-command: npm run test 